spring.application.name=ccr
camunda.bpm.client.base-url=http://localhost:8080/engine-rest
# Configuration for the community REST client starter
camunda.bpm.remote-rest-endpoint=http://localhost:8080/engine-rest
spring.cloud.compatibility-verifier.enabled=false
server.port=8082